### ISSUE TITLE
request to be added to the developers

### ISSUE THREAD

**Issue by hroskes** [cms-trackeralign/cmssw#1]
Hi,
I would like to be added to the developers for cms-trackeralign.  I would like to put back in the phases for the systematic misalignment tool, which was deleted by accident
https://hypernews.cern.ch/HyperNews/CMS/get/tif-alignment/223/1.html
and also my work on the cosmic track splitting validation, which I am planning to present on tomorrow
https://indico.cern.ch/event/305402/#2014-05-29
Thanks,
Heshy

**Comment by ghellwig** [comment]
Done!
