### ISSUE TITLE
add a developer

### ISSUE THREAD

**Issue by tlampen** [cms-trackeralign/cmssw#3]
Hi,
Can you add Terhi Järvinen (terhi.jarvinen@cern.ch, "terhi") to the developers?  I understood this is necessary so that she can get the latest version of all-in-one tool for 53X.
Cheers,
   Tapio

**Comment by ghellwig** [comment]
Just added you to the admin (owner) group. I think, that's appropriate for a convener :)

**Comment by tlampen** [comment]
Thanks Gregor!

**Comment by ghellwig** [comment]
Btw, for reading the repository it is not needed, to be developer.

**Comment by tlampen** [comment]
Ok, yes indeed, thanks for pointing this out.  -Tapio
